home:
    path: /
    controller: App\Controller\HomeController::index

property:
    path: /property
    controller: App\Controller\PropertyController::index


controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
